/**
 * Customer Wrapper for ObservePoint CSM Toolbelt Library
 * 
 * This file connects your Google Sheet to the ObservePoint Toolbelt library.
 * The library contains all the tools - this just creates the menu.
 * 
 * Library Script ID: 1v4DTpf5lRrNk1g4V4P9k1QYpfRMTolkHXP5BENkD36gzt1dF8XjuFjcS
 * 
 * AUTO-GENERATED - Do not edit manually
 * Generated by: scripts/generate-customer-template.sh
 * Menu structure synced from: src/Main.js
 */

// Create menu when sheet opens
function onOpen() {
  var ui = SpreadsheetApp.getUi();
  
  ui.createMenu('ObservePoint Tools')
    .addSubMenu(ui.createMenu('Grid API Importer')
      .addItem('Import Saved Report', 'gridImporter_importReport')
      .addItem('Clear Data', 'gridImporter_clearData'))
    .addSubMenu(ui.createMenu('Webhook Automation')
      .addItem('Setup Wizard', 'webhooks_setupWizard')
      .addItem('Manual Run Primary', 'webhooks_manualRunPrimary')
      .addItem('Manual Run Secondary', 'webhooks_manualRunSecondary')
      .addItem('Initialize Config', 'webhooks_initConfig'))
    .addSubMenu(ui.createMenu('Sitemap Monitor')
      .addItem('Setup & Run Monitor', 'sitemapMonitor_showSetupDialog')
      .addItem('Run Monitor', 'sitemapMonitor_runMonitor')
      .addItem('Initialize Config', 'sitemapMonitor_initConfig'))
    .addSeparator()
    .addItem('Initialize All Configs', 'initializeAllConfigs')
    .addItem('View Execution Log', 'showExecutionLog')
    .addItem('Clear Execution Log', 'clearExecutionLog')
    .addToUi();
}

// ============================================================================
// Wrapper Functions - Call library functions
// ============================================================================

function clearExecutionLog() {
  ObservePointTools.clearExecutionLog();
}

function gridImporter_clearData() {
  ObservePointTools.gridImporter_clearData();
}

function gridImporter_importReport() {
  // Show dialog from customer code (has getUi() access)
  const config = ObservePointTools.getGridImporterConfig();
  const html = ObservePointTools.getGridImporterDialogHtml(config);
  const htmlOutput = HtmlService.createHtmlOutput(html).setWidth(550).setHeight(600);
  SpreadsheetApp.getUi().showModalDialog(htmlOutput, 'Grid API Importer Setup');
}

// Dialog callback - must be in customer code
function saveGridImporterConfigAndImport(apiKey, reportId, batchSize, maxPages) {
  ObservePointTools.saveGridImporterConfigAndImport(apiKey, reportId, batchSize, maxPages);
}

function initializeAllConfigs() {
  ObservePointTools.initializeAllConfigs();
}

function showExecutionLog() {
  ObservePointTools.showExecutionLog();
}

function sitemapMonitor_initConfig() {
  ObservePointTools.sitemapMonitor_initConfig();
}

function sitemapMonitor_runMonitor() {
  ObservePointTools.sitemapMonitor_runMonitor();
}

function sitemapMonitor_showSetupDialog() {
  ObservePointTools.sitemapMonitor_showSetupDialog();
}

function webhooks_initConfig() {
  ObservePointTools.webhooks_initConfig();
}

function webhooks_manualRunPrimary() {
  ObservePointTools.webhooks_manualRunPrimary();
}

function webhooks_manualRunSecondary() {
  ObservePointTools.webhooks_manualRunSecondary();
}

function webhooks_setupWizard() {
  ObservePointTools.webhooks_setupWizard();
}

// ============================================================================
// Webhook Endpoint (if using Web App deployment)
// ============================================================================

function doPost(e) {
  return ObservePointTools.doPost(e);
}
