/**
 * Customer Wrapper for ObservePoint CSM Toolbelt Library
 * 
 * This file connects your Google Sheet to the ObservePoint Toolbelt library.
 * The library contains all the tools - this just creates the menu.
 * 
 * Library Script ID: 1v4DTpf5lRrNk1g4V4P9k1QYpfRMTolkHXP5BENkD36gzt1dF8XjuFjcS
 * 
 * AUTO-GENERATED - Do not edit manually
 * Generated by: scripts/generate-customer-template.sh
 */

// Create menu when sheet opens
function onOpen() {
  var ui = SpreadsheetApp.getUi();
  
  // Grid API Importer submenu
  var gridMenu = ui.createMenu('Grid API Importer');
  gridMenu.addItem('Clear Data', 'gridImporter_clearData')
    .addItem('Import Report', 'gridImporter_importReport')
    .addItem('Init Config', 'gridImporter_initConfig')
    .addItem('Run Import After Config', 'gridImporter_runImportAfterConfig')
    .addItem('Show Log', 'gridImporter_showLog')
  
  // Webhook Automation submenu
  var webhookMenu = ui.createMenu('Webhook Automation');
  webhookMenu.addItem('Init Config', 'webhooks_initConfig')
    .addItem('Manual Run Primary', 'webhooks_manualRunPrimary')
    .addItem('Manual Run Secondary', 'webhooks_manualRunSecondary')
    .addItem('Setup Wizard', 'webhooks_setupWizard')
  
  // Build the main menu
  var menu = ui.createMenu('ObservePoint Tools')
    .addSubMenu(gridMenu)
    .addSubMenu(webhookMenu)
    .addSeparator();
  menu.addItem('Clear Execution Log', 'clearExecutionLog');
  menu.addItem('Initialize All Configs', 'initializeAllConfigs');
  menu.addItem('Show Execution Log', 'showExecutionLog');
  
  menu.addToUi();
}

// ============================================================================
// Grid API Importer Wrapper Functions
// ============================================================================

function gridImporter_clearData() {
  ObservePointTools.gridImporter_clearData();
}

function gridImporter_importReport() {
  ObservePointTools.gridImporter_importReport();
}

function gridImporter_initConfig() {
  ObservePointTools.gridImporter_initConfig();
}

function gridImporter_runImportAfterConfig() {
  ObservePointTools.gridImporter_runImportAfterConfig();
}

function gridImporter_showLog() {
  ObservePointTools.gridImporter_showLog();
}

// ============================================================================
// Webhook Automation Wrapper Functions
// ============================================================================

function webhooks_initConfig() {
  ObservePointTools.webhooks_initConfig();
}

function webhooks_manualRunPrimary() {
  ObservePointTools.webhooks_manualRunPrimary();
}

function webhooks_manualRunSecondary() {
  ObservePointTools.webhooks_manualRunSecondary();
}

function webhooks_setupWizard() {
  ObservePointTools.webhooks_setupWizard();
}

// ============================================================================
// Utility Wrapper Functions
// ============================================================================

function clearExecutionLog() {
  ObservePointTools.clearExecutionLog();
}

function initializeAllConfigs() {
  ObservePointTools.initializeAllConfigs();
}

function showExecutionLog() {
  ObservePointTools.showExecutionLog();
}

// ============================================================================
// Webhook Endpoint (if using Web App deployment)
// ============================================================================

function doPost(e) {
  return ObservePointTools.doPost(e);
}
