/**
 * Customer Wrapper for ObservePoint CSM Toolbelt Library
 * 
 * This file connects your Google Sheet to the ObservePoint Toolbelt library.
 * The library contains all the tools - this just creates the menu.
 * 
 * Library Script ID: 1v4DTpf5lRrNk1g4V4P9k1QYpfRMTolkHXP5BENkD36gzt1dF8XjuFjcS
 * 
 * AUTO-GENERATED - Do not edit manually
 * Generated by: scripts/generate-customer-template.sh
 * Menu structure synced from: src/Main.js
 */

// Create menu when sheet opens
function onOpen() {
  var ui = SpreadsheetApp.getUi();
  
  // IMPORTANT: When changing this menu structure, also update:
  // 1. scripts/generate-customer-template.sh (auto-generates customer-template/Code.js)
  // 2. src/CustomerSheetManager.js > generateCustomerWrapperCode() function
  // Run: ./scripts/generate-customer-template.sh after changes
  
  ui.createMenu('ObservePoint Tools')
    .addSubMenu(ui.createMenu('Grid API Importer')
      .addItem('Initialize Config', 'gridImporter_initConfig')
      .addItem('Import Saved Report', 'gridImporter_importReport')
      .addItem('Clear Data', 'gridImporter_clearData'))
    .addSubMenu(ui.createMenu('Webhook Automation')
      .addItem('Setup Wizard', 'webhooks_setupWizard')
      .addItem('Manual Run Primary', 'webhooks_manualRunPrimary')
      .addItem('Manual Run Secondary', 'webhooks_manualRunSecondary')
      .addItem('Initialize Config', 'webhooks_initConfig'))
    .addSubMenu(ui.createMenu('Sitemap Monitor')
      .addItem('Initialize Config', 'sitemapMonitor_initConfig')
      .addItem('Run Monitor', 'sitemapMonitor_runMonitor'))
    .addSeparator()
    .addItem('Initialize All Configs', 'initializeAllConfigs')
    .addItem('View Execution Log', 'showExecutionLog')
    .addItem('Clear Execution Log', 'clearExecutionLog')
    .addToUi();
}

// ============================================================================
// Wrapper Functions - Call library functions
// ============================================================================

function clearExecutionLog() {
  ObservePointTools.clearExecutionLog();
}

function gridImporter_clearData() {
  ObservePointTools.gridImporter_clearData();
}

function gridImporter_importReport() {
  ObservePointTools.gridImporter_importReport();
}

function gridImporter_initConfig() {
  ObservePointTools.gridImporter_initConfig();
}

function initializeAllConfigs() {
  ObservePointTools.initializeAllConfigs();
}

function showExecutionLog() {
  ObservePointTools.showExecutionLog();
}

function sitemapMonitor_initConfig() {
  ObservePointTools.sitemapMonitor_initConfig();
}

function sitemapMonitor_runMonitor() {
  ObservePointTools.sitemapMonitor_runMonitor();
}

function webhooks_initConfig() {
  ObservePointTools.webhooks_initConfig();
}

function webhooks_manualRunPrimary() {
  ObservePointTools.webhooks_manualRunPrimary();
}

function webhooks_manualRunSecondary() {
  ObservePointTools.webhooks_manualRunSecondary();
}

function webhooks_setupWizard() {
  ObservePointTools.webhooks_setupWizard();
}

// ============================================================================
// Webhook Endpoint (if using Web App deployment)
// ============================================================================

/**
 * Webhook handler with lock protection
 * Lock is handled here (not in library) to prevent cross-customer conflicts
 */
function doPost(e) {
  var lock = LockService.getScriptLock();
  
  try {
    // Try to acquire lock for 30 seconds
    var hasLock = lock.tryLock(30000);
    
    if (!hasLock) {
      // Another webhook is processing, return early
      return ContentService.createTextOutput('Processing in progress, skipped duplicate')
        .setMimeType(ContentService.MimeType.TEXT);
    }
    
    // Call library function with lock held
    return ObservePointTools.doPost(e);
    
  } catch (err) {
    Logger.log('Webhook error: ' + err.message);
    return ContentService.createTextOutput('Error: ' + err.message)
      .setMimeType(ContentService.MimeType.TEXT);
      
  } finally {
    // Always release lock
    if (lock) {
      lock.releaseLock();
    }
  }
}
