#!/bin/bash

# Auto-generate customer template Code.js by parsing Main.js menu structure
# This ensures the customer template menu exactly matches the library menu

TEMPLATE_DIR="customer-template"
OUTPUT_FILE="$TEMPLATE_DIR/Code.js"
MAIN_FILE="src/Main.js"

echo "🔧 Generating customer template Code.js from Main.js menu structure..."

# Extract the onOpen function from Main.js
# We'll parse it to get the menu structure, excluding Customer Management submenu
ONOPEN_FULL=$(sed -n '/^function onOpen()/,/^}/p' "$MAIN_FILE")

# Remove the Customer Management submenu and its separator
# This removes from the Customer Management line through the closing paren and next separator
ONOPEN_CONTENT=$(echo "$ONOPEN_FULL" | sed '/addSubMenu(ui.createMenu.*Customer Management/,/addSeparator()/{ /addSubMenu(ui.createMenu.*Customer Management/d; /addSeparator()/d; /addItem.*Customer/d; }'  | sed '/checkForOutdatedSheets/d' | sed '/viewCustomerSheetRegistry/d' | sed '/showCreateCustomerSheetDialog/d')

# Extract all function names referenced in the menu (excluding Customer Management functions)
ALL_FUNCTIONS=$(echo "$ONOPEN_CONTENT" | grep -o "'[a-zA-Z_]*'" | tr -d "'" | grep -E "^(gridImporter_|webhooks_|sitemapMonitor_|initializeAllConfigs|showExecutionLog|clearExecutionLog)" | sort -u)

# Generate the Code.js file header
cat > "$OUTPUT_FILE" << 'EOF'
/**
 * Customer Wrapper for ObservePoint CSM Toolbelt Library
 * 
 * This file connects your Google Sheet to the ObservePoint Toolbelt library.
 * The library contains all the tools - this just creates the menu.
 * 
 * Library Script ID: 1v4DTpf5lRrNk1g4V4P9k1QYpfRMTolkHXP5BENkD36gzt1dF8XjuFjcS
 * 
 * AUTO-GENERATED - Do not edit manually
 * Generated by: scripts/generate-customer-template.sh
 * Menu structure synced from: src/Main.js
 */

EOF

# Copy the onOpen function from Main.js, preserving the exact structure
echo "// Create menu when sheet opens" >> "$OUTPUT_FILE"
echo "$ONOPEN_CONTENT" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << 'EOF'
// ============================================================================
// Wrapper Functions - Call library functions
// ============================================================================

EOF

# Generate wrapper functions for all discovered functions
for func in $ALL_FUNCTIONS; do
  cat >> "$OUTPUT_FILE" << EOF
function $func() {
  ObservePointTools.$func();
}

EOF
done

cat >> "$OUTPUT_FILE" << 'EOF'
// ============================================================================
// Webhook Endpoint (if using Web App deployment)
// ============================================================================

/**
 * Webhook handler with lock protection
 * Lock is handled here (not in library) to prevent cross-customer conflicts
 */
function doPost(e) {
  var lock = LockService.getScriptLock();
  
  try {
    // Try to acquire lock for 30 seconds
    var hasLock = lock.tryLock(30000);
    
    if (!hasLock) {
      // Another webhook is processing, return early
      return ContentService.createTextOutput('Processing in progress, skipped duplicate')
        .setMimeType(ContentService.MimeType.TEXT);
    }
    
    // Call library function with lock held
    return ObservePointTools.doPost(e);
    
  } catch (err) {
    Logger.log('Webhook error: ' + err.message);
    return ContentService.createTextOutput('Error: ' + err.message)
      .setMimeType(ContentService.MimeType.TEXT);
      
  } finally {
    // Always release lock
    if (lock) {
      lock.releaseLock();
    }
  }
}
EOF

echo "✅ Generated $OUTPUT_FILE with menu structure from Main.js"
echo ""
echo "📋 Functions included: $(echo "$ALL_FUNCTIONS" | wc -l | tr -d ' ') wrapper functions"
echo "🔄 Menu structure synced from src/Main.js (Customer Management excluded)"
