#!/bin/bash

# Auto-generate customer template Code.js based on library functions
# This ensures the template always has all the latest menu items and wrappers

TEMPLATE_DIR="customer-template"
OUTPUT_FILE="$TEMPLATE_DIR/Code.js"

echo "🔧 Generating customer template Code.js..."

# Extract all public functions from library source files
# Look for functions that start with specific prefixes
GRID_FUNCTIONS=$(grep -h "^function gridImporter_" src/*.js | sed 's/function \([^(]*\).*/\1/' | sort -u)
WEBHOOK_FUNCTIONS=$(grep -h "^function webhooks_" src/*.js | sed 's/function \([^(]*\).*/\1/' | sort -u)
UTILITY_FUNCTIONS=$(grep -h "^function \(initializeAllConfigs\|showExecutionLog\|clearExecutionLog\)" src/*.js | sed 's/function \([^(]*\).*/\1/' | sort -u)

# Generate the Code.js file
cat > "$OUTPUT_FILE" << 'EOF'
/**
 * Customer Wrapper for ObservePoint CSM Toolbelt Library
 * 
 * This file connects your Google Sheet to the ObservePoint Toolbelt library.
 * The library contains all the tools - this just creates the menu.
 * 
 * Library Script ID: 1v4DTpf5lRrNk1g4V4P9k1QYpfRMTolkHXP5BENkD36gzt1dF8XjuFjcS
 * 
 * AUTO-GENERATED - Do not edit manually
 * Generated by: scripts/generate-customer-template.sh
 */

// Create menu when sheet opens
function onOpen() {
  var ui = SpreadsheetApp.getUi();
  
  // Grid API Importer submenu
  var gridMenu = ui.createMenu('Grid API Importer');
EOF

# Add Grid Importer menu items
FIRST=true
for func in $GRID_FUNCTIONS; do
  # Convert function name to menu label (e.g., gridImporter_importReport -> Import Report)
  LABEL=$(echo "$func" | sed 's/gridImporter_//' | sed 's/\([A-Z]\)/ \1/g' | sed 's/^ //' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2));}1')
  if [ "$FIRST" = true ]; then
    echo "  gridMenu.addItem('$LABEL', '$func')" >> "$OUTPUT_FILE"
    FIRST=false
  else
    echo "    .addItem('$LABEL', '$func')" >> "$OUTPUT_FILE"
  fi
done

cat >> "$OUTPUT_FILE" << 'EOF'
  
  // Webhook Automation submenu
  var webhookMenu = ui.createMenu('Webhook Automation');
EOF

# Add Webhook menu items
FIRST=true
for func in $WEBHOOK_FUNCTIONS; do
  LABEL=$(echo "$func" | sed 's/webhooks_//' | sed 's/\([A-Z]\)/ \1/g' | sed 's/^ //' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2));}1')
  if [ "$FIRST" = true ]; then
    echo "  webhookMenu.addItem('$LABEL', '$func')" >> "$OUTPUT_FILE"
    FIRST=false
  else
    echo "    .addItem('$LABEL', '$func')" >> "$OUTPUT_FILE"
  fi
done

cat >> "$OUTPUT_FILE" << 'EOF'
  
  // Build the main menu
  var menu = ui.createMenu('ObservePoint Tools')
    .addSubMenu(gridMenu)
    .addSubMenu(webhookMenu)
    .addSeparator();
EOF

# Add utility menu items
for func in $UTILITY_FUNCTIONS; do
  LABEL=$(echo "$func" | sed 's/\([A-Z]\)/ \1/g' | sed 's/^ //' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2));}1')
  echo "  menu.addItem('$LABEL', '$func');" >> "$OUTPUT_FILE"
done

cat >> "$OUTPUT_FILE" << 'EOF'
  
  menu.addToUi();
}

// ============================================================================
// Grid API Importer Wrapper Functions
// ============================================================================

EOF

# Generate wrapper functions for Grid Importer
for func in $GRID_FUNCTIONS; do
  cat >> "$OUTPUT_FILE" << EOF
function $func() {
  ObservePointTools.$func();
}

EOF
done

cat >> "$OUTPUT_FILE" << 'EOF'
// ============================================================================
// Webhook Automation Wrapper Functions
// ============================================================================

EOF

# Generate wrapper functions for Webhooks
for func in $WEBHOOK_FUNCTIONS; do
  cat >> "$OUTPUT_FILE" << EOF
function $func() {
  ObservePointTools.$func();
}

EOF
done

cat >> "$OUTPUT_FILE" << 'EOF'
// ============================================================================
// Utility Wrapper Functions
// ============================================================================

EOF

# Generate wrapper functions for utilities
for func in $UTILITY_FUNCTIONS; do
  cat >> "$OUTPUT_FILE" << EOF
function $func() {
  ObservePointTools.$func();
}

EOF
done

cat >> "$OUTPUT_FILE" << 'EOF'
// ============================================================================
// Webhook Endpoint (if using Web App deployment)
// ============================================================================

function doPost(e) {
  return ObservePointTools.doPost(e);
}
EOF

echo "✅ Generated $OUTPUT_FILE with all library functions"
echo ""
echo "📋 Functions included:"
echo "  Grid Importer: $(echo "$GRID_FUNCTIONS" | wc -l | tr -d ' ') functions"
echo "  Webhooks: $(echo "$WEBHOOK_FUNCTIONS" | wc -l | tr -d ' ') functions"
echo "  Utilities: $(echo "$UTILITY_FUNCTIONS" | wc -l | tr -d ' ') functions"
